### ISSUE TITLE
Combine BBL and ST

### ISSUE THREAD

**Issue by tilaye** [tilaye/MelaNetDataSt#10]
- Combine training files for BBL and ST datasets
- Randomize it
- Do the same for valid files
- Store as BBLST dataset
- Put on S3

**Comment by tilayealemu** [comment]
https://github.com/tilayealemu/MelaNetData/commit/8a20a9eab5a14e6294936a833af4ae6f5d2fa6a6

**Comment by tilaye** [comment]
https://github.com/tilayealemu/MelaNetDataStbbl
